version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "ember",
    "vue",
    "angular",
    "meteor",
    "angularjs",
    "react"
  ]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "16"