name: Deployment

on:
  push:
    branches: [ dev ]
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn clean packahe -Pproduction
    - name: Heroku Build

      uses: behe/heroku-build@v1
      with:
          app-name: ${{secrets.HEROKU_APP}}
          api-key: ${{secrets.HEROKU_API_KEY}}
